/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2021-09-08 04:18:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/include/../music/music_modal.jspf", Long.valueOf(1609262972000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <span class=\"copyright\">Spring framework Web Project</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <ul class=\"list-inline social-buttons\">\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\" style=\"background-color: #643691;\">\r\n");
      out.write("                <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\" style=\"background-color: #643691;\">\r\n");
      out.write("                <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\" style=\"background-color: #643691;\">\r\n");
      out.write("                <i class=\"fab fa-linkedin-in\"></i>\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("          <ul class=\"list-inline quicklinks\">\r\n");
      out.write("            <li class=\"list-inline-item\">\r\n");
      out.write("              <a href=\"#\">BTS 공식카페</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  <!-- Modal La Vie en Rose -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"lavieenrose\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">라비앙 로즈 MV</h4>\r\n");
      out.write("        <button class=\"close\" type=\"button\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/WZwr2a_lFWY\"></iframe>\r\n");
      out.write("       \r\n");
      out.write("      </div>      \r\n");
      out.write("     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <!-- Modal La Vie en Rose-2 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"lavieenrose-2\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">라비앙 로즈 교차편집</h4>\r\n");
      out.write("        <button class=\"close\" type=\"button\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/HIaoU5UZghQ\"></iframe>\r\n");
      out.write("  \r\n");
      out.write("      </div>      \r\n");
      out.write("     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Modal Violeta -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"violeta\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">비올레타 MV</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/6eEZ7DJMzuk\"></iframe>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Modal Violeta-2 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"violeta-2\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">비올레타 교차편집</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/ml_0KpFAEhY\"></iframe>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("    <!-- Modal Fiesta -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"fiesta\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">피에스타 MV</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/eDEFolvLn0A\"></iframe>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("   </div> \r\n");
      out.write("   \r\n");
      out.write("    <!-- Modal Fiesta-2 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"fiesta-2\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">피에스타 교차편집</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/DQ2JmI1G0lk\"></iframe>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("       <!-- Modal 환상동화 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"swan\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">피에스타 교차편집</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/nnVjsos40qk\"></iframe>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("       <!-- Modal 환상동화-2 -->\r\n");
      out.write("  <div class=\"modal fade\" id=\"swan-2\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">피에스타 교차편집</h4>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Modal body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <iframe class=\"embed-responsive-item\" width=\"100%\" height=\"600\" src=\"https://www.youtube.com/embed/mqgv2jL0TiI\"></iframe>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("	</div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
